"""initial migration

Revision ID: 04c44383601f
Revises: 
Create Date: 2025-12-09 23:36:26.550891

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '04c44383601f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('street', sa.String(length=255), nullable=False),
                    sa.Column('city', sa.String(length=100), nullable=False),
                    sa.Column('state', sa.String(length=100), nullable=False),
                    sa.Column('postal_code', sa.String(
                        length=20), nullable=False),
                    sa.Column('country', sa.String(
                        length=100), nullable=False),
                    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326,
                                                                     dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.create_index('idx_addresses_location', [
                              'location'], unique=False, postgresql_using='gist')

    op.create_table('job_categories',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('skills',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('username', sa.String(
                        length=150), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('password', sa.String(
                        length=255), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username')
                    )
    op.create_table('companies',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('address_id', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['address_id'], ['addresses.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user_skills',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('skill_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('user_id', 'skill_id')
                    )
    op.create_table('job_posts',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('title', sa.String(length=255), nullable=False),
                    sa.Column('description', sa.Text(), nullable=False),
                    sa.Column('job_category_id', sa.Integer(), nullable=False),
                    sa.Column('company_id', sa.Integer(), nullable=False),
                    sa.Column('salary', sa.Float(), nullable=False),
                    sa.Column('salary_type', sa.String(
                        length=20), nullable=True),
                    sa.Column('address_id', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['address_id'], ['addresses.id'], ),
                    sa.ForeignKeyConstraint(
                        ['company_id'], ['companies.id'], ),
                    sa.ForeignKeyConstraint(['job_category_id'], [
                                            'job_categories.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('job_post_skills',
                    sa.Column('required', sa.Boolean(), nullable=False),
                    sa.Column('job_post_id', sa.Integer(), nullable=False),
                    sa.Column('skill_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['job_post_id'], ['job_posts.id'], ),
                    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
                    sa.PrimaryKeyConstraint('job_post_id', 'skill_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_post_skills')
    op.drop_table('job_posts')
    op.drop_table('user_skills')
    op.drop_table('companies')
    op.drop_table('users')
    op.drop_table('skills')
    op.drop_table('job_categories')
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_index('idx_addresses_location', postgresql_using='gist')

    op.drop_table('addresses')
    # ### end Alembic commands ###
