"""update chatting related models

Revision ID: 1ce95d3fc0b1
Revises: 97800851825b
Create Date: 2026-04-02 22:34:28.555758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ce95d3fc0b1'
down_revision = '97800851825b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_post_id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_post_id'], ['job_posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('applicant_id', 'job_post_id', name='unique_applicant_per_job_post')
    )
    op.create_index(op.f('ix_conversations_applicant_id'), 'conversations', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_conversations_job_post_id'), 'conversations', ['job_post_id'], unique=False)
    op.create_table('conversation_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'user_id', name='unique_user_per_conversation')
    )
    op.create_index(op.f('ix_conversation_participants_conversation_id'), 'conversation_participants', ['conversation_id'], unique=False)
    op.add_column('messages', sa.Column('conversation_id', sa.Integer(), nullable=False))
    op.add_column('messages', sa.Column('sender_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_foreign_key('fk_messages_sender_id', 'messages', 'users', ['sender_id'], ['id'])
    op.create_foreign_key('fk_messages_conversation_id', 'messages', 'conversations', ['conversation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_messages_conversation_id', 'messages', type_='foreignkey')
    op.drop_constraint('fk_messages_sender_id', 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_column('messages', 'sender_id')
    op.drop_column('messages', 'conversation_id')
    op.drop_index(op.f('ix_conversation_participants_conversation_id'), table_name='conversation_participants')
    op.drop_table('conversation_participants')
    op.drop_index(op.f('ix_conversations_job_post_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_applicant_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
