"""installed fastapi

Revision ID: 1efda5621113
Revises: 723512ab558e
Create Date: 2026-02-04 17:07:09.564874

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1efda5621113'
down_revision = '723512ab558e'
branch_labels = None
depends_on = None


def upgrade():
    # Drop dependent tables first
    op.drop_table('user_messages')
    op.drop_table('job_post_skills')
    op.drop_table('user_skills')
    op.drop_table('company_members')
    op.drop_table('job_posts')

    # Then drop the tables they depended on
    op.drop_index(op.f('ix_messages_timestamp'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('companies')
    op.drop_index(op.f('idx_addresses_location'),
                  table_name='addresses', postgresql_using='gist')
    op.drop_table('addresses')
    op.drop_table('skills')
    op.drop_table('users')
    op.drop_table('job_categories')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_categories',
                    sa.Column('id', sa.INTEGER(), server_default=sa.text(
                        "nextval('job_categories_id_seq'::regclass)"), autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=255),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='job_categories_pkey'),
                    postgresql_ignore_search_path=False
                    )
    op.create_table('companies',
                    sa.Column('id', sa.INTEGER(), server_default=sa.text(
                        "nextval('companies_id_seq'::regclass)"), autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=255),
                              autoincrement=False, nullable=False),
                    sa.Column('address_id', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=True),
                    sa.Column('deleted_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(
                        ['address_id'], ['addresses.id'], name='companies_address_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='companies_pkey'),
                    postgresql_ignore_search_path=False
                    )
    op.create_table('users',
                    sa.Column('id', sa.INTEGER(), server_default=sa.text(
                        "nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
                    sa.Column('username', sa.VARCHAR(length=150),
                              autoincrement=False, nullable=False),
                    sa.Column('email', sa.VARCHAR(length=255),
                              autoincrement=False, nullable=False),
                    sa.Column('password', sa.VARCHAR(length=255),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=True),
                    sa.Column('deleted_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='users_pkey'),
                    sa.UniqueConstraint('email', name='users_email_key', postgresql_include=[
                    ], postgresql_nulls_not_distinct=False),
                    sa.UniqueConstraint('username', name='users_username_key', postgresql_include=[
                    ], postgresql_nulls_not_distinct=False),
                    postgresql_ignore_search_path=False
                    )
    op.create_table('user_messages',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('message_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('job_post_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('role', postgresql.ENUM('sender', 'recipient',
                                                      name='message_role'), autoincrement=False, nullable=False),
                    sa.Column('read_at', postgresql.TIMESTAMP(timezone=True),
                              autoincrement=False, nullable=True),
                    sa.Column('deleted_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['job_post_id'], ['job_posts.id'], name=op.f(
                        'user_messages_job_post_id_fkey')),
                    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f(
                        'user_messages_message_id_fkey')),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f(
                        'user_messages_user_id_fkey')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('user_messages_pkey')),
                    sa.UniqueConstraint('user_id', 'message_id', name=op.f(
                        'unique_user_per_message'), postgresql_include=[], postgresql_nulls_not_distinct=False)
                    )
    op.create_table('skills',
                    sa.Column('id', sa.INTEGER(), server_default=sa.text(
                        "nextval('skills_id_seq'::regclass)"), autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=255),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='skills_pkey'),
                    postgresql_ignore_search_path=False
                    )
    op.create_table('addresses',
                    sa.Column('id', sa.INTEGER(), server_default=sa.text(
                        "nextval('addresses_id_seq'::regclass)"), autoincrement=True, nullable=False),
                    sa.Column('street', sa.VARCHAR(length=255),
                              autoincrement=False, nullable=False),
                    sa.Column('city', sa.VARCHAR(length=100),
                              autoincrement=False, nullable=False),
                    sa.Column('state', sa.VARCHAR(length=100),
                              autoincrement=False, nullable=False),
                    sa.Column('postal_code', sa.VARCHAR(length=20),
                              autoincrement=False, nullable=False),
                    sa.Column('country', sa.VARCHAR(length=100),
                              autoincrement=False, nullable=False),
                    sa.Column('location', Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT',
                                                   name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True),
                    sa.Column('geocode_status', postgresql.ENUM('pending', 'success',
                                                                'failed', name='geocode_status'), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='addresses_pkey'),
                    postgresql_ignore_search_path=False
                    )
    op.create_index(op.f('idx_addresses_location'), 'addresses', [
                    'location'], unique=False, postgresql_using='gist')
    op.create_table('user_skills',
                    sa.Column('user_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('skill_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(
                        ['skill_id'], ['skills.id'], name=op.f('user_skills_skill_id_fkey')),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], name=op.f('user_skills_user_id_fkey')),
                    sa.PrimaryKeyConstraint('user_id', 'skill_id',
                                            name=op.f('user_skills_pkey'))
                    )
    op.create_table('job_post_skills',
                    sa.Column('required', sa.BOOLEAN(),
                              autoincrement=False, nullable=False),
                    sa.Column('job_post_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('skill_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['job_post_id'], ['job_posts.id'], name=op.f(
                        'job_post_skills_job_post_id_fkey')),
                    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f(
                        'job_post_skills_skill_id_fkey')),
                    sa.PrimaryKeyConstraint('job_post_id', 'skill_id',
                                            name=op.f('job_post_skills_pkey'))
                    )
    op.create_table('job_posts',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('title', sa.VARCHAR(length=255),
                              autoincrement=False, nullable=False),
                    sa.Column('description', sa.TEXT(),
                              autoincrement=False, nullable=False),
                    sa.Column('job_category_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('company_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('salary', sa.DOUBLE_PRECISION(precision=53),
                              autoincrement=False, nullable=False),
                    sa.Column('salary_type', sa.VARCHAR(length=20),
                              autoincrement=False, nullable=True),
                    sa.Column('address_id', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=True),
                    sa.Column('deleted_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(
                        ['address_id'], ['addresses.id'], name=op.f('job_posts_address_id_fkey')),
                    sa.ForeignKeyConstraint(
                        ['company_id'], ['companies.id'], name=op.f('job_posts_company_id_fkey')),
                    sa.ForeignKeyConstraint(['job_category_id'], ['job_categories.id'], name=op.f(
                        'job_posts_job_category_id_fkey')),
                    sa.PrimaryKeyConstraint('id', name=op.f('job_posts_pkey'))
                    )
    op.create_table('company_members',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('company_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f(
                        'company_members_company_id_fkey')),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f(
                        'company_members_user_id_fkey')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('company_members_pkey')),
                    sa.UniqueConstraint('user_id', 'company_id', name=op.f(
                        'unique_user_per_company'), postgresql_include=[], postgresql_nulls_not_distinct=False)
                    )
    op.create_table('messages',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('body', sa.VARCHAR(length=140),
                              autoincrement=False, nullable=True),
                    sa.Column('timestamp', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f('messages_pkey'))
                    )
    op.create_index(op.f('ix_messages_timestamp'),
                    'messages', ['timestamp'], unique=False)
    # ### end Alembic commands ###
