"""added JobApplication model

Revision ID: 8320ebe9e266
Revises: a0e16147fd34
Create Date: 2026-03-06 20:36:28.286865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8320ebe9e266'
down_revision = 'a0e16147fd34'
branch_labels = None
depends_on = None

application_status_enum = sa.Enum(
    'APPLIED', 'REVIEWING', 'REJECTED', 'ACCEPTED', 'WITHDRAWN', name='application_status'
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    application_status_enum.create(op.get_bind(), checkfirst=True)
    op.create_table('job_applications',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('job_post_id', sa.Integer(), nullable=False),
                    sa.Column('application_status',
                              application_status_enum, nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['job_post_id'], ['job_posts.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    )
    op.create_index('unique_active_application_per_user_job', 'job_applications', [
                    'user_id', 'job_post_id'], unique=True, postgresql_where=sa.text("application_status IN ('APPLIED', 'REVIEWING')"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_active_application_per_user_job', table_name='job_applications',
                  postgresql_where=sa.text("application_status IN ('APPLIED', 'REVIEWING')"))
    op.drop_table('job_applications')
    application_status_enum.drop(op.get_bind(), checkfirst=True)
# ### end Alembic commands ###
