"""initial

Revision ID: a0e16147fd34
Revises: 
Create Date: 2026-02-20 19:06:49.023706

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography

# revision identifiers, used by Alembic.
revision = 'a0e16147fd34'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('street', sa.String(length=255), nullable=False),
                    sa.Column('city', sa.String(length=100), nullable=False),
                    sa.Column('state', sa.String(length=100), nullable=False),
                    sa.Column('postal_code', sa.String(
                        length=20), nullable=False),
                    sa.Column('country', sa.String(
                        length=100), nullable=False),
                    sa.Column('location', Geography(geometry_type='POINT', srid=4326, dimension=2,
                                                    from_text='ST_GeogFromText', name='geography'), nullable=True),
                    sa.Column('geocode_status', sa.Enum('pending', 'success',
                                                        'failed', name='geocode_status'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('idx_addresses_location', 'addresses', [
                    'location'], unique=False, postgresql_using='gist')
    op.create_table('job_categories',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('messages',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('body', sa.String(length=140), nullable=False),
                    sa.Column('timestamp', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_messages_timestamp'),
                    'messages', ['timestamp'], unique=False)
    op.create_table('skills',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('username', sa.String(
                        length=150), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('password', sa.String(
                        length=255), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username')
                    )
    op.create_table('companies',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('address_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('deleted_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['address_id'], ['addresses.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user_skills',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('skill_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('user_id', 'skill_id')
                    )
    op.create_table('company_members',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('company_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['company_id'], ['companies.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('user_id', 'company_id',
                                        name='unique_user_per_company')
                    )
    op.create_table('job_posts',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('title', sa.String(length=255), nullable=False),
                    sa.Column('description', sa.Text(), nullable=False),
                    sa.Column('job_category_id', sa.Integer(), nullable=False),
                    sa.Column('company_id', sa.Integer(), nullable=False),
                    sa.Column('salary', sa.Float(), nullable=False),
                    sa.Column('salary_type', sa.String(
                        length=20), nullable=False),
                    sa.Column('address_id', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('deleted_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['address_id'], ['addresses.id'], ),
                    sa.ForeignKeyConstraint(
                        ['company_id'], ['companies.id'], ),
                    sa.ForeignKeyConstraint(['job_category_id'], [
                                            'job_categories.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('job_post_skills',
                    sa.Column('required', sa.Boolean(), nullable=False),
                    sa.Column('job_post_id', sa.Integer(), nullable=False),
                    sa.Column('skill_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['job_post_id'], ['job_posts.id'], ),
                    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
                    sa.PrimaryKeyConstraint('job_post_id', 'skill_id')
                    )
    op.create_table('user_messages',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('message_id', sa.Integer(), nullable=False),
                    sa.Column('job_post_id', sa.Integer(), nullable=False),
                    sa.Column('role', sa.Enum('sender', 'recipient',
                                              name='message_role'), nullable=False),
                    sa.Column('read_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['job_post_id'], ['job_posts.id'], ),
                    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('user_id', 'message_id',
                                        name='unique_user_per_message')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_messages')
    op.drop_table('job_post_skills')
    op.drop_table('job_posts')
    op.drop_table('company_members')
    op.drop_table('user_skills')
    op.drop_table('companies')
    op.drop_table('users')
    op.drop_table('skills')
    op.drop_index(op.f('ix_messages_timestamp'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('job_categories')
    op.drop_index('idx_addresses_location',
                  table_name='addresses', postgresql_using='gist')
    op.drop_table('addresses')
    # ### end Alembic commands ###
